// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7twydXUuD9aoyzNI-0lOFGb1WIun4ocs',
    appId: '1:56539368933:web:fa324df5ec01c1cefdf30c',
    messagingSenderId: '56539368933',
    projectId: 'flutter-al-quran',
    authDomain: 'flutter-al-quran.firebaseapp.com',
    storageBucket: 'flutter-al-quran.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUxU15tHlw21NfBMDMpwuQYkQkIgGrAX8',
    appId: '1:56539368933:android:3a4ffac68265c653fdf30c',
    messagingSenderId: '56539368933',
    projectId: 'flutter-al-quran',
    storageBucket: 'flutter-al-quran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMtBubSbFN6t4PMQZpRFdc-GYIAP1Fcvo',
    appId: '1:56539368933:ios:b548c26f28a3eda2fdf30c',
    messagingSenderId: '56539368933',
    projectId: 'flutter-al-quran',
    storageBucket: 'flutter-al-quran.firebasestorage.app',
    iosBundleId: 'com.harithya.alquran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMtBubSbFN6t4PMQZpRFdc-GYIAP1Fcvo',
    appId: '1:56539368933:ios:b7af504857af67d2fdf30c',
    messagingSenderId: '56539368933',
    projectId: 'flutter-al-quran',
    storageBucket: 'flutter-al-quran.firebasestorage.app',
    iosBundleId: 'com.example.alquran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7twydXUuD9aoyzNI-0lOFGb1WIun4ocs',
    appId: '1:56539368933:web:1095d5f042583e9efdf30c',
    messagingSenderId: '56539368933',
    projectId: 'flutter-al-quran',
    authDomain: 'flutter-al-quran.firebaseapp.com',
    storageBucket: 'flutter-al-quran.firebasestorage.app',
  );

}