name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Profile)
        run: flutter build apk --profile

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-profile-apk
          path: build/app/outputs/flutter-apk/app-profile.apk

      - name: Push and Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-profile.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v0.0.${{ github.run_number }}
